###############################################################################
# DB credentials in Secrets Manager.
#
# - Password is generated by Terraform; never stored in tfvars or passed
#   as input.
# - Secret value is a JSON blob {username, password, host, port, dbname}
#   so the app can pull a single secret and get everything it needs.
# - recovery_window_in_days = 0 means "delete immediately on destroy"
#   which keeps `terraform destroy` clean for a learning project. In prod,
#   set this to 7-30 to allow undelete.
###############################################################################

resource "random_password" "db" {
  length  = 32
  special = true
  # RDS rejects '/', '@', '"', and ' ' in master passwords.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "db" {
  name_prefix             = "${local.name_prefix}/db/"
  description             = "Postgres master credentials for ${local.name_prefix}"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    host     = aws_db_instance.app.address
    port     = aws_db_instance.app.port
    dbname   = var.db_name
  })
}
